#!/usr/bin/env python3

import http.server
import socketserver
import sys
import subprocess

def get_ip_addresses():
    ip_addresses = []
    local_ip = subprocess.check_output("hostname -I", shell=True).decode().strip()
    ip_addresses.extend(local_ip.split(" "))
    return ip_addresses

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python -m qsend <file>")
        sys.exit(1)

    file_to_send = sys.argv[1]
    ip_addresses = get_ip_addresses()

    for ip in ip_addresses:
        print(f"curl -O http://{ip}:8000/{file_to_send}")

    handler = http.server.SimpleHTTPRequestHandler
    with socketserver.TCPServer(("", 8000), handler) as httpd:
        print("Serving at port 8000")
        httpd.serve_forever()
    